### ISSUE TITLE
Current Status of Project and Future

### ISSUE THREAD

**Issue by JonReagan** [jichu4n/pilot-link#1]
Hello,

What is the current status of this project?  I have been dusting off some older Palm Pilots but have not been able to find this software in the Ubuntu repositories.  I used it a long time ago but would like to try my hand at installing it on a modern system.  If there are technical limitations, I'd like to assist in trying to make it compatible with updated packages. 

All the best,
Jon

**Comment by jichu4n** [comment]
Hi @JonReagan ! I am not affiliated with the original pilot-link.org developers and this project is just an unofficial mirror of the pilot-link source code. So I'm afraid I don't have much to offer here 😞
